### ISSUE TITLE
StormpathUser.USERNAME_FIELD does not match with StormpathBackend.authenticate

### ISSUE THREAD

**Issue by skolsuper** [stormpath/stormpath-django#18]
I am trying to use stormpath with json webtoken authentication in a django rest framework app using https://github.com/GetBlimp/django-rest-framework-jwt.  When dealing with a request for a token, drf-jwt tries to guess the username field like so:

```
class JSONWebTokenSerializer(Serializer):
...
@property
    def username_field(self):
        User = utils.get_user_model()
        try:
            return User.USERNAME_FIELD
        except AttributeError:
        return 'username'

    def validate(self, attrs):
        credentials = {self.username_field: attrs.get(self.username_field),
        'password': attrs.get('password')}
        if all(credentials.values()):
            user = authenticate(**credentials)
```

However, since StormpathBackend.authenticate looks for 'username' and 'password' kwargs and USERNAME_FIELD on the StormpathUser model is 'email', django.contrib.auth.authenticate always returns None.

**Comment by denibertovic** [comment]
This is solved in #19

**Comment by skolsuper** [comment]
It would help me a lot of this issue was fixed in the pypi package (am trying to deploy on heroku and getting it to use my fork is a bit of a pain)

**Comment by rdegges** [comment]
Bam, just pushed the new release. Good to go!

Sorry for lagging on this, I've been wayyy behind as I've got a ton of PR / issues on many of the repos I maintain ><
