### ISSUE TITLE
Travis tests are noop

### ISSUE THREAD

**Issue by senko** [stormpath/stormpath-django#22]
Investigating why #21 (update: fixed #20 -> #21 reference) wasn't caught by our automated tests that ostensibly test 2.x, 3.x and pypy, I found out that our Travis config doesn't have `STORMPATH_API_KEY_{ID,SECRET}` set, thus shortcutting test runner and always succeeding.

For example, look at all the test runs in this build: https://travis-ci.org/stormpath/stormpath-django/builds/50395943 (latest at the time of this writing)

I assume the secret environent variables from `.travis.yml` are incorrectly signed (it looks like they were just copied from `stormpath-sdk-python` repository, but it's possible they have to be regenerated for a different repo), so Travis ignores them.

As I believe fixing this requires admin access to Travis for the repo, @rdegges could you please look into it?

**Comment by rdegges** [comment]
Dude. Good catch. I recently screwed this up in another project as well ><

Fixed.
