### ISSUE TITLE
Provide first_name / last_name Compatibility

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-django#35]
Right now we aren't providing a way for third-party Django apps that depend on the *normal* user model to interact with our user model's first_name and last_name fields.

The core Django user model provides:

- `first_name`
- `last_name`
- `email`
- `password`

Our model is almost identical, but has `given_name` and `surname`.

To make our integration work better with other third-party Django apps, we *need* to provide getters / setters for `first_name` and `last_name` that transparently update `given_name` and `surname` behind the scenes.

I for some reason thought this was already in here, but I'm not seeing the codez. Hrm.

@avojnovicDk can you take a look at this and prioritize it? We've got a user who needs this functionality.

Thanks!

**Comment by avojnovicDk** [comment]
Hi, @rdegges !
Just to check - `given_name` and `surname` (and, of course, `middle_name`) should still work?

**Comment by rdegges** [comment]
Yep!

**Comment by rdegges** [comment]
Closing this as this has been released in 1.0.2.
