### ISSUE TITLE
Django versions supported

### ISSUE THREAD

**Issue by ErikEvenson** [stormpath/stormpath-django#54]
Unlike the python version, the README does not indicate what Django versions are supported.  Based on the Travis comment in the version 1.0.2, it seems that 1.6+ is supported.  This should be explicitly stated in the Meta section if true.

Thanks!

**Comment by ErikEvenson** [comment]
Since djanog-stormpath uses migrations, it seems that 1.6 is not supported.

**Comment by avojnovicDk** [comment]
Hey @ErikEvenson, you are right - README was missing supported Django versions info. 1.6+ is actually supported - django-stormpath uses migrations, but it also has south_migrations folder to support Django 1.6.

**Comment by rdegges** [comment]
Closing this as it is now reflected in our docs =)
