### ISSUE TITLE
Add Method to Pull All Accounts Into Local Database

### ISSUE THREAD

**Issue by pnovotnak** [stormpath/stormpath-django#72]
I'd be happy to contribute this functionality if it doesn't exist. Where should I start?

**Comment by rdegges** [comment]
So, what's the use case for this? Right now, this happens automatically when a user logs into their account.

Let's say that you've got a Stormpath application with 100 accounts, and a brand new Django database with 0 accounts.

When a user logs into your Django app using their Stormpath credentials, we'll:

- Check Stormpath to authenticate the user.
- If the user is found, we'll COPY the user's information into the local Django database with an unusable password.
- This way, the user is available both on Stormpath AND in Django.

Does that make sense?

**Comment by pnovotnak** [comment]
Right right, I understand how the user model is populated from stormpath and persisted to the database.

I want to query users that will exist in stormpath but will never log in to the Django site.

**Comment by rdegges** [comment]
Ah, ok.

Well, in that case, yes -- I'd be totally open to merging in some sort of management command or something like that which would do this.

Maybe something like `django-admin.py sync_stormpath` or something similar? I'd write it as a management command, and just have it use the Stormpath credentials from `settings.py` to connect to the Stormpath Application, iterate through the user accounts, and create them locally in Django with unusable passwords.

**Comment by pnovotnak** [comment]
Yeah, that's what I'm thinking.

I'm thinking `models.StormpathUserManager` should get a function `sync_stormpath` that calls `models.CLIENT.accounts()`, iterating over them and adding or updating where required. Does that sound kosher?

Setting the passwords to blank passwords shouldn't [prevent them from logging in, right](https://github.com/stormpath/stormpath-django/blob/master/django_stormpath/backends.py#L94)?

This is starting to float up my priorities list, I should have some code for a PR sometime soon.

**Comment by rdegges** [comment]
I think what you should do instead is find the correct Application, eg:

```python
app = models.CLIENT.directories.get(settings.STORMPATH_APPLICATION)

for account in app.accounts:
   # ... sync ...
```

This way, if you have multiple Stormpath Applications, you won't pull down Accounts that AREN'T a part of your Application =)

**Comment by rdegges** [comment]
Also: for passwords, I'd use this: https://docs.djangoproject.com/en/1.9/ref/contrib/auth/#django.contrib.auth.models.User.set_unusable_password

**Comment by javierbq** [comment]
@rdegges: could you give a look to #78? we are currently vendoring the module due to the slow response we are getting from stormpath on this issue.
